name: .NET

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        file: [Youtube2MP3, Youtube2MP3.exe]
        include:
          - os: ubuntu-latest
            file: Youtube2MP3.exe
            rid: linux-x64
          - os: windows-latest
            file: Youtube2MP3
            rid: win-x64
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      working-directory: ./Youtube2MP3
      run: dotnet publish -c Release -r {{ matrix.rid }} --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: Relase ${{ github.ref }}
        prerelease: true
        files: Youtube2MP3/bin/Debug/net5.0/${{ matrix.file }}
        
